### ISSUE TITLE
0pdd didn't raise the issues for the puzzlers which exists in "snapshot" xml

### ISSUE THREAD

**Issue by dgroup** [yegor256/0pdd#241]
Hi @yegor256 ,

The project was linked with 0pdd
1. `.0pdd` content
    ```bash
      --source=.
      --verbose
      --exclude target/**/*
      --exclude docs
      --rule min-estimate:30
      --rule max-estimate:90
   ```
2. `.0pdd.yml` content
    ```yml
     errors:
        - yurii.dubinka@gmail.com
     # alerts:
        #  suppress:
        #    - on-found-puzzle
        #    - on-lost-puzzle
        #    - on-scope
        #  github:
        #    - dgroup
        #format:
        #  - short-title
        #  - title-length=100
    
     tags:
       - pdd
       - bug
    ```
3. @0pdd addes as contributor
4. The integration hook also configured
<img width="764" alt="screen shot 2018-09-22 at 3 14 18 pm" src="https://user-images.githubusercontent.com/1651114/45915869-608de680-be7a-11e8-87e7-85a8f349cdf3.png">

According to http://www.0pdd.com/p?name=dgroup/ka25 
there are 2 active issues from `todo.md` file, but it was removed as not required long time ago.

According to http://www.0pdd.com/snapshot?name=dgroup/ka25
there are 2 pendind puzzlers which should be created.

I've pushed several commits, but there is no action from @0pdd side.
Expected result:
1. The following puzzlers are removed
    http://www.0pdd.com/p?name=dgroup/ka25
    ```
     7-18f0c0e2 todo.md:2-2 30min
     8-f87da0bd todo.md:3-3 30min
   ```
2. The 2 issues are raised for the `14-9ca373f0` and `13-23e31113` accordinly.
