### ISSUE TITLE
notify users on new puzzles

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#31]
Let's make it possible to configure in `.0pdd.yml` the list of users who should get notifications when new puzzles are posted. We should just post an extra message to them, asking to pay attention to the ticket. Something like this:

```yaml
alerts:
  github:
    - yegor256
    - davvd
```

These two people will get a notification message: @yegor256 and @davvd
