### ISSUE TITLE
Can't connect `0pdd` to `jsmith` repository

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/0pdd#702]
I have the [jsmith](https://github.com/volodya-lombrozo/jsmith) repository with the following `.0pdd.yaml` configuration:

```yaml
threshold: 256
model: true
alerts:
  suppress:
    - on-found-puzzle
    - on-lost-puzzle
    - on-scope
  github:
    - volodya-lombrozo
format:
  - short-title
  - title-length=100
tags:
  - pdd
  - bug
```

Also I added a web-hook:

**Payload URL ***
```
https://p.rehttp.net/https://www.0pdd.com/hook/github
```

**Content type ***
```
application/json
```

Also I added a `pdd` [GitHub action](https://github.com/volodya-lombrozo/jsmith/blob/main/.github/workflows/pdd.yml):

```
---
name: pdd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pdd:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: volodya-lombrozo/pdd-action@master
```

**Actual behaviour:** When I push new puzzles into main brach, nothing happens.
**Expected behaviour:** When I push new puzzles into main brach, the new puzzles are successfully created.
